#Max Frame Rate matching monitor Hz
#dxgi.maxFrameRate = 165
#d3d9.maxFrameRate = 165

#Disable VSync
dxgi.syncInterval = 0
d3d9.presentInterval = 0

dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1
